server:
  port: 8080
  servlet:
      context-path: /bootcamp

spring:
  datasource:
    driver-clase-name: org.postgresql.Driver
    url: postgres://gvbhhojefuqice:4d9002d6d889076a274317d336f9394ec6a7eb1298056769697696b2779eb758@ec2-54-158-232-223.compute-1.amazonaws.com:5432/d99bbgb5ar9971
    username: gvbhhojefuqice
    password: 4d9002d6d889076a274317d336f9394ec6a7eb1298056769697696b2779eb758
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      
application:
  description: Projeto criado para o bootcamp DIO - Santander