server:
  port: 8080
  servlet:
      context-path: /bootcamp

spring:
  datasource:
    driver-clase-name: org.postgresql.Driver
    url: postgres://vrdepzhbmeoumb:1e80ab14cbee35ab231c659e6670c08ad6902a14c2b3022189461f03cb44cc3e@ec2-3-218-71-191.compute-1.amazonaws.com:5432/d2dda8acbk2ag9
    username: vrdepzhbmeoumb
    password: 1e80ab14cbee35ab231c659e6670c08ad6902a14c2b3022189461f03cb44cc3e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      

