server:
  port: 8080
  servlet:
      context-path: /bootcamp

spring:
  datasource:
    driver-clase-name: org.postgresql.Driver
    url:  postgres://cjquznzthskbca:5f412b2d572935b68c88ccd81cf710cdde8fb037204f182485fe16a738cfe50b@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d9a3hvi3qpro6u
    username: cjquznzthskbca
    password: 5f412b2d572935b68c88ccd81cf710cdde8fb037204f182485fe16a738cfe50b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      
  application:
    description: Projeto criado para o bootcamp DIO - Santander

  
  
  
deployment:
  staging:
    branch: main
    commands:
        git remote add heroku git@heroku.com:herokuapplicationname.git
        "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
        cd ../../.. && git subtree push --prefix GitHubPath/to/application heroku master